// Code generated by config-getters; DO NOT EDIT.

package config

// Config Getters

func (c Config) GetBaseURL() string {
	return c.BaseURL
}

func (c Config) GetEnvironment() string {
	return c.Environment
}

func (c Config) GetImages() Images {
	return c.Images
}

func (c Config) GetName() string {
	return c.Name
}

// Fs Getters

func (f Fs) GetBasePath() string {
	return f.BasePath
}

// Images Getters

func (i Images) GetFs() Fs {
	return i.Fs
}

func (i Images) GetS3() S3 {
	return i.S3
}

// S3 Getters

func (s S3) GetBasePath() string {
	return s.BasePath
}

func (s S3) GetBucket() string {
	return s.Bucket
}

func (s S3) GetEndpointURL() string {
	return s.EndpointURL
}

func (s S3) GetProfile() string {
	return s.Profile
}

func (s S3) GetRegion() string {
	return s.Region
}
