// Code generated by app-config; DO NOT EDIT.

package config

type Config struct {
	BaseURL     string `json:"base_url" koanf:"base_url"`
	Environment string `json:"environment" koanf:"environment"`
	Images      Images `json:"images" koanf:"images"`
	Name        string `json:"name" koanf:"name"`
}

type Fs struct {
	BasePath string `json:"base_path" koanf:"base_path"`
}

type Images struct {
	Fs Fs `json:"fs" koanf:"fs"`
	S3 S3 `json:"s3" koanf:"s3"`
}

type S3 struct {
	BasePath    string `json:"base_path" koanf:"base_path"`
	Bucket      string `json:"bucket" koanf:"bucket"`
	EndpointURL string `json:"endpoint_url" koanf:"endpoint_url"`
	Profile     string `json:"profile" koanf:"profile"`
	Region      string `json:"region" koanf:"region"`
}
